# Generated by Django 4.2.23 on 2025-08-05 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('Trained', 'Trained')], default='Trained', max_length=20)),
                ('vector_store', models.CharField(choices=[('FAISS', 'FAISS'), ('CHROMA', 'CHROMA')], default='FAISS', max_length=50)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rags',
            },
        ),
        migrations.CreateModel(
            name='RagFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('public_url', models.TextField()),
                ('hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rag.rag')),
            ],
            options={
                'db_table': 'rag_files',
            },
        ),
    ]
